### ISSUE TITLE
First-time user issues: Github login is briefly shown, error in OCL example

### ISSUE THREAD

**Issue by agarciadom** [mdenet/educationplatform-docker#2]
I've just tried this new approach. While the instructions worked well, I noticed two issues:

1. After clicking on an activity, the Github login screen is briefly shown to the user before we go into the main UI. This could confuse a first-time user, who could think that the app is malfunctioning in some way.
2. While the Epsilon example worked well from the start, running the OCL example with no changes results in an error ("There was an error translating action function parameter types"). See the screenshot below.

![image](https://github.com/mdenet/educationplatform-docker/assets/46504/37770346-9680-4766-9dbd-8e1f26e15467)

**Comment by agarciadom** [comment]
Looking at the README again, I realise the OCL part has to be built and launched separately. That was a bit surprising for me - it'd be good to have that as part of the Docker image building.

**Comment by barnettwilliam** [comment]
Added a separate issue for 2. - #8
